[package]
name = "rpm-builder"
version = "0.8.0"
authors = ["Rene Richter <richterrettich@gmail.com>"]
edition = "2018"
build= "build.rs"

[dependencies]
rpm-rs = "0.8.0"
clap= "2"
chrono = "0.4"
regex = "1"

[build-dependencies]
clap = "2"
